name: Build release image with cache
description: Builds the Docker release image using GitHub Actions cache for optimal performance
inputs:
  app_name:
    description: Name of application folder under infra directory
    required: true
outputs:
  image_name:
    description: The full image name
    value: ${{ steps.get-image-info.outputs.image_name }}
  image_tag:
    description: The image tag
    value: ${{ steps.get-image-info.outputs.image_tag }}
  full_image:
    description: The full image reference (name:tag)
    value: ${{ steps.get-image-info.outputs.full_image }}
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get image info
      id: get-image-info
      shell: bash
      run: |
        IMAGE_NAME=$(make APP_NAME=${{ inputs.app_name }} release-image-name)
        IMAGE_TAG=$(make release-image-tag)
        echo "image_name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
        echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
        echo "full_image=$IMAGE_NAME:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
        echo "Building image: $IMAGE_NAME:$IMAGE_TAG"

    - name: Build release image with cache
      uses: docker/build-push-action@v5
      with:
        context: ./${{ inputs.app_name }}
        push: false
        load: true
        tags: |
          ${{ steps.get-image-info.outputs.image_name }}:latest
          ${{ steps.get-image-info.outputs.image_name }}:${{ steps.get-image-info.outputs.image_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          RUN_USER=${{ env.USER }}
          RUN_UID=1001
