// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnchorScrollController from "./anchor_scroll_controller"
application.register("anchor-scroll", AnchorScrollController)

import Cbv__AttestationCheckController from "./cbv/attestation_check_controller"
application.register("cbv--attestation-check", Cbv__AttestationCheckController)

import Cbv__BackButtonController from "./cbv/back_button_controller"
application.register("cbv--back-button", Cbv__BackButtonController)

import Cbv__EntryPageController from "./cbv/entry_page_controller"
application.register("cbv--entry-page", Cbv__EntryPageController)

import Cbv__SessionsController from "./cbv/sessions_controller"
application.register("cbv--sessions", Cbv__SessionsController)

import Cbv__SessionsTimeoutController from "./cbv/sessions_timeout_controller"
application.register("cbv--sessions-timeout", Cbv__SessionsTimeoutController)

import Cbv__SynchronizationsController from "./cbv/synchronizations_controller"
application.register("cbv--synchronizations", Cbv__SynchronizationsController)

import ClickTrackerController from "./click_tracker_controller"
application.register("click-tracker", ClickTrackerController)

import CopyLinkController from "./copy_link_controller"
application.register("copy-link", CopyLinkController)

import LanguageController from "./language_controller"
application.register("language", LanguageController)

import PollingController from "./polling_controller"
application.register("polling", PollingController)

import PreviewFormController from "./preview_form_controller"
application.register("preview-form", PreviewFormController)

import PreviewToggleController from "./preview_toggle_controller"
application.register("preview-toggle", PreviewToggleController)

import ScrollResetController from "./scroll_reset_controller"
application.register("scroll-reset", ScrollResetController)
